### ISSUE TITLE
Viewport height (vh) is unstable on iPad / Chrome

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/seda-map#106]
You may recall we had this issue on EL, where because the browser toolbar comes in and out of view when you scroll on iPad + Chrome (possibly other browsers too), the vh number will change depending on whether or not that toolbar is in view. It causes a stuttering and resizing of vh-based elements.

Seeing this on scatterplots, etc. as one scrolls down, and it's fairly disruptive to the experience. Didn't we implement a fix for this for EL?

**Comment by Lane** [comment]
yep, thanks for logging.  will fix this issue when I get to the mobile layouts.

**Comment by Lane** [comment]
page no longer scrolls, not needed
