### ISSUE TITLE
Search display when results for an entry exceed 5

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/seda-map#117]
Would be good to somehow extend the search results for common-named places beyond 5. Seems to be mostly an issue for schools.

For common place names, e.g. Springfield, I'm thinking a user can continue refining by adding the state name (e.g. Georgia) for these? That seems to work with the interface.

Adding the state to a school name (e.g. Springfield Elementary) for search refinement does not seem to be an option.

**Comment by Lane** [comment]
Agree being able to enter state name to narrow down results would be nice.  Currently the state name is not in the search data, so it doesn't filter any further if you type the state.  I will add states into the search index on algolia.
