### ISSUE TITLE
Search sometimes produces unrelated and redundant results

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/seda-map#118]
Try entering "Lincoln" into search. Scroll down to Schools in results and you'll see 5 entries for Lincoln, New Jersey.

Then select from that list—say, Lincoln Public Schools. The next card that pops up has "Lincoln Public Schools" prepopulated, and then a bunch of other selections below it that are unrelated (e.g. NYC Public Schools).

**Comment by Lane** [comment]
@james-minton we have two issues happening here:

**1. Too many matches for schools at a national level.**  
Here is a cut of all of the schools with the name "Lincoln" in the data set: https://gist.github.com/Lane/a138bdfd8c91b8a096e1cc4e8af8f29d

There are 30 in New Jersey alone, many are just named "LINCOLN".  I'm not sure what to do about this issue.

**2. Irrelevant results after selection**
The input is supposed to reset after selection and the box should disappear.  The results you're seeing are the ones you'd get if you searched an empty string.  I will fix that up so the box and results clear properly.
