### ISSUE TITLE
High level directions & questions from 5/8 SEDA call

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/seda-map#163]
**Global**
- Change intro screen into a full screen popup, seen on landing only
- Move map/chart/both toggle to main body of the tool
- For map & chart views, create a “preview” window to display a small (and reciprocally interactive) version of inactive tool, which is graphically linked to the “view toggle” button assigned to activate that tool.
- Add a “What does this mean?” button that triggers a left-to-right-opening “drawer” (or window overlay) panel containing both standard text and conditional text specific to user selections / view

**Map view**
- Create interactive horizontal color legend for map choropleths
- Create interactive legend for secondary variable (e.g. SES)
- Add SES variable to tooltips on map
    - Make this as concise as possible

**Achievement Gap & Opportunity Differences**
- Adapt scatterplot and map for displaying achievement gaps
    - Allow access to this view via subheader controls?
        - How to do this? 
            - Add a menu in this subheader allowing selection of either SES or Segregation Measure? And then allow selection of either default [key parameter] display or “[between-demographic] gap”? In this case, what do we call the default (non-gap) selection?
    - Alternate option is to have separate “tabs” for 1) main Key Parameters view, 2) Achievement Gaps, and 3) Opportunity Differences
        - Issues:
            - Creates more buttons / choice / complexity
            - Current thinking is that Opportunity Differences would not have map component. Does it make sense, then, to group that in with the other displays that do have maps? 
    - Or should Opportunity Differences be set off as its own, unique kind of selection?
        - How to access? 
            - Special button?
            - And / or suggestion to view this somewhere in the side robotext panel?

**Location selections**
- These populate as tabs at bottom of screen. 
    - By default, only location and color indicator are shown
    - Hovering causes them to rise up and display either
        - shortform data display (a couple of data points)
        - longform display with all data
- Optionally, a button is added to “view all data”
    - This either raises up all columns for selected locations, or triggers scroll-down to see full side-by-side data display

**View Similar Places**
- Add as an option within location cards
    - Triggers popup listing 5 selectable locations
        - Selection within popup adds location to cards, map, and chart
        - This popup should have a bit of text at bottom with a very brief overview of criteria for “similarity,” with link to FAQ question—or maybe just the latter?

**Link sharing**
- Custom shareable links
    - Links are populated with current user selections (locations / metrics)
        - Button to copy link 
        - Button to email the link
- Link sharing via social media
    - Connects to Twitter / Facebook API for quick posting
        - Should these shares on Twitter be prepopulated with conditional text based on location, or generic text?
            - James might vote for more generic, as the complexities of the data and number of locations make for very byzantine conditionals that could strain our best efforts at syntactical coherence, and / or exceed even the new 280 character limit
            - Note that this is only an option for Twitter in any case; Facebook’s API is more restrictive about including preformatted text

**Export** 
- Custom embedding on external websites 
    - Clicking activates popup with selections for
        - Embed map
        - Embed scatterplot
    - Currently selected locations / metrics will be active in the embed
    - How interactive will the embed be? E.g. can users change key metrics, or do we limit it just the user-configured display?
- Custom shareable links
    - Links are populated with current user selections (locations / metrics)
- PDF & PPT
    - Question: what do we include for each location?
        - Map?
        - Scatterplot?
        - All data points?
    - To keep this from sprawling on forever (we’re factoring in up to 7 locations!), should we limit map and scatterplot outputs here to just what the user has configured? And let a full table of data points complete the picture for other, non-displayed metrics?

**Comment by Lane** [comment]
great!  i think we can keep this issue open at a high level.  i have a milestone with issues for these tasks in the [UI Revisions Milestone]()

i have labelled all of the issues in the milestone that need a spec/wireframe so maybe it makes sense for us all to meet up and put together functional specifications / rough sketches for the features that need it?

Here is an index of issues to the items mentioned above:

- Change intro screen into a full screen popup, seen on landing only (see #159)
- Move map/chart/both toggle to main body of the tool (see #139)
- For map & chart views, create a “preview” window (see #139 and #156)
- Add a “What does this mean?” button (see #155)
- Create interactive horizontal color legend for map choropleths (see #156)
- Create secondary interactive legend for secondary variable (e.g. SES) (see #156)
- Add SES variable to tooltips on map (see #158)
- Adapt scatterplot and map for displaying achievement gaps (see #153 and #154)
- Allow access to this view via subheader controls? (see #152)
- Alternate option is to have separate “tabs” (see #152)
- Location selections (see #157)
- View Similar Places (see #79)
- Custom shareable links (see #163)    
- Link sharing via social media(see #78) 
- Custom embedding on external websites (see #141)
- PDF (see #77)

In addition to these, didn't Sean say something about a powerpoint?  I have made issue #162, but can close if we're not doing that.

**Comment by Lane** [comment]
closing, all of these have been wrapped into other issues
