### ISSUE TITLE
"Button press" animation in Explorer cycles repeatedly

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/seda-map#198]
**Describe the bug**

Client reports that after selecting a primary metric, or view (e.g. "map"), then switching to another window, then switching back to the Explorer, the "expanding circle" animation on those buttons gets stuck in a loop. It's a visual bug, but functionality still works.

**To Reproduce**

Click on any of the mentioned buttons in Explorer, switch to another window, then return to Explorer.

**Expected behavior**

"Button press animation" should happen once and not cycle repeatedly.

**Desktop (please complete the following information):**

Client demonstrated in Firefox / Windows. (I can't reproduce same on Mac.)

**Comment by Lane** [comment]
this is the focus state for the button, when leaving the tab and re-entering focus is restored to the last pressed element.  the next interaction will clear the focus state and stop the animation.
