### ISSUE TITLE
Data filters

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/seda-map#329]
# Specification

client has requested the ability to filter dots on the chart based on size. 

- user can select what size filter they would like to apply:
  - for counties, there will be a size filter with options:
    - top 100 largest
    - all
  - for districts, there will be a size filter with options:
    - top 100 largest
    - next 900 largest
    - all
  - for schools, there will be no size filter
- the size filter should compound with any existing filtering by state. (e.g. if the user has selected to show school districts in California and the top 100 largest, it should show the top 100 largest in California)

# Current Status

one option presented by @Peterlollo:

> I think we could add a conditionally rendered dropdown which allows users to select from different sizing options — the options would be dependent upon whether a user is filtering by County or District. If a user is filtering by School, the dropdown would be hidden. Otherwise, the dropdown would appear “after” the dropdown which allows filtering by US state. (“After” meaning to the right of the US state dropdown for large screens, and below the US state dropdown on small screens...)

this is a good option when space is available next to the "selected state" filter, however some special consideration will need to be made for lower resolution devices where there not be space for the additional component (tablet portait ~768px -> tablet landscape ~1024px)

**Comment by Lane** [comment]
was thinking about this a bit.  perhaps replacing the state filter with a "more filters" button that breaks filtering into a dialog might work?  similar to what google does in maps:

![image](https://user-images.githubusercontent.com/21034/69276980-ab011500-0b9c-11ea-96dc-978e1ef380c1.png)

**Comment by Peterlollo** [comment]
A "More filters" dialog seems like a good option. Currently, the map has a similar implementation for smalls screens. Clicking the "Average test scores" button pulls up a dialog for filtering the data:
<img width="619" alt="Screen Shot 2019-11-20 at 1 18 25 PM" src="https://user-images.githubusercontent.com/14285286/69279102-82771c00-0b98-11ea-99cf-bedea4a735af.png">
 


I could add a "More Filters" button which triggers this existing dialog. I'd need to modify the dialog slightly: adding the new size filter, and perhaps only conditionally rendering the other "Metrics" portion of the dialog.
Existing dialog:
<img width="497" alt="Screen Shot 2019-11-20 at 1 25 34 PM" src="https://user-images.githubusercontent.com/14285286/69279463-409aa580-0b99-11ea-972d-405f979c1038.png">

**Comment by Lane** [comment]
yeah i like that idea :+1:

**Comment by james-minton** [comment]
One small thing:

> the size filter should compound with any existing filtering by state. (e.g. if the user has selected to show school districts in California and the top 100 largest, it should show the top 100 largest in California)

This would be more applicable to schools, of which there are hundreds per state. However, some states have as few as 16 districts (e.g. Delaware) so showing the top 100 isn't helpful. How about we change it to top 10 districts if a state is selected? 

Counties are another issue -- Hawaii, for example, has 1 county. Wonder if we should just disable size filtering for these entirely? (Grey out the "more filters" modal trigger if a state is selected?)

**Comment by james-minton** [comment]
### Revised Specification (12/18/19)

Add ability within the Opportunity Explorer to filter data by:

- Districts:
    - [ ]  size:
        - 10 largest
        - 100 largest
        - 1000 largest
    - [ ]  By state (size filter carries through)
- Counties:
    - [ ]  Size:
        - 10 largest
        - 100 largest
    - [ ]  By state (size filter carries through)
- Schools:
    - [ ]  Filter by state
    - [ ]  Filter by district
    - [ ]  Middle | elementary | combined (need data)
    - [ ]  Charter vs traditional public | magnet (need data)
    - [ ]  Rural | suburban | urban (need data)
- [ ]  Add same filtering to map

**Notes:** 

- The size filter should compound with any existing filtering by state. (e.g. if the user has selected to show school districts in California and the top 100 largest, it should show the top 100 largest in California).
- Size filtering is always derived from "all students" and not affected by demographic/gap selections

**Next Steps**
- Discuss larger-scope redesign of Explorer UI for a new release that bundles in this and a number of other features  
- Work on back-end tasks (if any) that can be done independently of this redesign work

**Comment by james-minton** [comment]
**Potential further revision to specification:**

- add ability (at schools level) to filter NYC Public Schools by sub-districts (of which there are 32).

**Comment by Lane** [comment]
Need to check in with SEDA team about:
- showing schools within a district or county
- showing districts within a county

I thought Sean had said the schools / districts are prefixed with the fips code, but that doesn't seem to work.  (e.g. Cook County has a FIPS of 17013, but none of the schools / districts in Cook County start with 17013).

**Comment by Lane** [comment]
preview available on temporary link

still to do:
- indicator on sidebar to show number of active filters
- list active filters in tooltip on hover over filter icon
- revise "show largest" UI component (spec says use predetermined sizes instead of slider, will use a button group for this)
    - update size options on region selection

bugs to fix:
- selected location filter disappears when switching region, but remains in effect
- should clear location filter when switching to a region with higher geometry than the region (eg. clear district filter when switching to counties, there are no counties within a specific district)
- district choropleths are filtered at the same time as school dots
- resetting filters does not reset the selected location in the UI

**Comment by Lane** [comment]
Still to do

- [ ] group school / district toggles appropriately
- [ ] add language for filter names

**Comment by Lane** [comment]
closing, creating separate issues for remaining issues
