### ISSUE TITLE
Add states as geographic units

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/seda-map#340]
### Specification

Client has requested addition of states as units of analysis in chart + map.

### Next steps

- [x] Finalize overall revised 1.1.0 UI structure
- [x] Add new tasks to the pipeline for generating state level tilesets and chart data
- [x] Add options to the front end

**Comment by Lane** [comment]
- [ ] Set ranges for all subgroups on states
- [ ] Set ranges for sizes on all states
- [ ] Add metadata for states to render tooltips properly

**Comment by Lane** [comment]
functionality added in #363
