### ISSUE TITLE
Explorer error/bug roundup

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/seda-map#342]
Hoping to address some bugs as part of v1.1.0:

mobile:

- [x] “atStanford University” on mobile load screen 
- [x] School comparison and Export are inaccessible on Chrome & Safari /iOS — bottom tab in browsers obscures these items

all screens:

- [x] Clicking “USA” button in zoom controls causes any location below it to be triggered
- [x] Clicking on “my location” in zoom controls behaves as expected. But if zooming out or in, user is returned to the previously-viewed area (Chrome/Mac).

**Comment by Lane** [comment]
one more for mobile:

text subtitle is centered when wrapping to a second line (should be left aligned)
![image](https://user-images.githubusercontent.com/21034/72487031-e5b4b180-37c9-11ea-9b75-9eaeafd5947f.png)

**Comment by laurendoone** [comment]
All are fixed except 1 issue. I'll close this ticket and create a new ticket to track that: https://github.com/Hyperobjekt/seda-map/issues/479
