### ISSUE TITLE
Add XLSX / CSV reports

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/seda-map#345]
It's been agreed that exports (Excel / CSV's) of data subsets could be useful.

To be determined:

- Increase allowable # of pinned locations (or remove the limit altogether) and use these as a basis for exports?
- And/or: use filters to allow exporting a larger sample at once? (Past a certain scale, this may tend to be impractical, so a sort of "capped" or "gated" filtering system could be needed.)

Next steps:

- [x] discuss options
- [x] develop mockup
- [ ] prototype, etc.

Priority at the moment is low-to-medium.

**Comment by Lane** [comment]
This feature has been integrated as part of #354

**Comment by Lane** [comment]
issue is now tracked by #376
