### ISSUE TITLE
Co-located schools can obscure one another on map

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/seda-map#346]
On the map, co-located schools are stacked atop each other so that only one is visible. 

Ex.: PS 506 and PS 503 in NYC.

Proposed solution: add step to data pipeline that shifts schools with same coordinates slightly apart.

Distance of separation can be such that schools should be distinguishable at an agreed-upon "average" zoom depth, but can continue to obscure each other at wider zooms.

**Comment by laurendoone** [comment]
Lane estimate: .5 days

**Comment by Lane** [comment]
shifted overlapping schools with the latest data build
