### ISSUE TITLE
Add street names 

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/seda-map#347]
At a level of zoom where it's practical, it would be nice to add street names to aid wayfinding.

**Comment by laurendoone** [comment]
TO DO: Login to mapbox studio account, modify the style that we're using for the Explorer

**Comment by sashasashasasha** [comment]
I can do this but don’t have the login details for the map box studio
account.

**Comment by laurendoone** [comment]
@sashasashasasha try these credentials:
user: hyperobjekt 
password: DqT9}fX}K!$TX8k&

Thank you!!

**Comment by laurendoone** [comment]
Remaining dev task: pull the road styles from the JSON export and integrate them into the style within our repo
