### ISSUE TITLE
Accessibility Updates

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/seda-map#364]
- [x] shift focus to appropriate element when opening panels (e.g. "close" button)
- [x] add `aria-hidden` to closed panels, ensure tabbing to hidden panels is not possible
- [ ] "esc" key closes panels
- [ ] add any missing focus / hover states
- [ ] add keyboard shortcuts (time permitting)

**Comment by laurendoone** [comment]
Out of scope: keyboard shortcuts
