### ISSUE TITLE
Embed functionality

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/seda-map#371]
Need to re-add embed functionality, similar to existing functionality at https://edopportunity.org/explorer

Refer to the existing code in the `production` branch and refactor to use the new state hooks instead of redux

- [ ] add embed dialog
- [ ] ensure that all previous embed links work with new URL routing structure
- [ ] create stripped down embed view

**Comment by laurendoone** [comment]
Connor estimate: 2 days
