### ISSUE TITLE
Create language google sheet

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/seda-map#388]
Currently, all language for the explorer is loaded from [en.js](https://github.com/Hyperobjekt/seda-map/blob/master/src/modules/explorer/app/constants/en.js)

This should be adjusted so it is a simple google sheet of key / value pairs, so it can be edited by the client.  A build step should be added that fetches the CSV on build and converts it to a JSON file that is loaded into the app.

**Comment by laurendoone** [comment]
From Lane:

i just dumped all of the language into a google sheet on drive to get you started.  https://docs.google.com/spreadsheets/d/1L633lO5wfQGLbaVnaSnIg9TrprX9k4Ie8qe_CLDmQN8/edit?usp=sharing

we're fetching data for the UCLA project from google sheets in a similar way, which you can look at here: https://github.com/Hyperobjekt/covid-19-behind-bars/blob/development/packages/gatsby-ucla-site/scripts/fetchData.js#L36

packages/gatsby-ucla-site/scripts/fetchData.js:36
const jailReleases = `https://docs.google.com/spreadsheets/d/1X6uJkXXS-O6eePLxw2e4JeRtM41uPZ2eRcOA_HkPVTk/export?gid=1678228533&format=csv`

<https://github.com/Hyperobjekt/covid-19-behind-bars|Hyperobjekt/covid-19-behind-bars>Hyperobjekt/covid-19-behind-bars 

the link to fetch the spreadsheet above as a CSV would be https://docs.google.com/spreadsheets/d/1L633lO5wfQGLbaVnaSnIg9TrprX9k4Ie8qe_CLDmQN8/export?gid=0&format=csv 

some of the formatting in the google sheet is messed up (e.g. language entries with line breaks are adding new rows when they shouldn't and commas are creating new columns when they shouldn't).  this will need to be fixed up, maybe by wrapping in single quotes? hopefully this is enough to get you going.  let me know if you have questions!
