### ISSUE TITLE
Explorer Mobile implementation

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/seda-map#390]
Need to arrange elements for mobile friendly view.  Should be similar to current mobile implementation, but the data options trigger opens the sidebar instead of a dialog.

**Comment by laurendoone** [comment]
Waiting on designs

**Comment by laurendoone** [comment]
@touchRED the approved Figma mockups here. Page - 'FINAL MOCKUPS'

**Comment by touchRED** [comment]
@laurendoone my estimate for this is that it will likely be wrapped up by EOD tomorrow – I've gotten a good start with the footer and side panel, so I'll be focusing mostly on the header tomorrow.

**Comment by touchRED** [comment]
@laurendoone update: lots of good progress today but still a few smaller things leftover – gonna circle back to them in the morning, hoping to have a PR in for this before our status meeting tomorrow
