### ISSUE TITLE
Mobile design

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#392]
We have been focusing mainly on the desktop version of the new EdOpportunity site, but will need to start implementing for mobile soon and need some help with designs, primarily with the new navigation, to make it mobile-friendly/responsive. 

This is one of the more recent versions of the staging site, for reference: http://edop-110-tmp.surge.sh/

The developers are hoping we can keep the mobile layout the same as the current explorer (see attached). it should work with our updated interface components. We'll probably need to:

- Move the side navigation to top navigation (or whatever is more user friendly for mobile)
- Update the footer so it fits on mobile
- Update the header so it fits on mobile

V1 design due: Thursday Jan 7

![image](https://user-images.githubusercontent.com/76966798/103684562-9e768200-4f40-11eb-9613-606d23746929.png)

**Comment by laurendoone** [comment]
@sashasashasasha here is the team's feedback on the draft - could you please let me know when it's updated so we can have one more review before it goes into development? thank you!!

- update site menu icon to be consistent with the rest of the pages on the site (we can update to your new icon site wide post launch if needed)
- for space concerns,  hide the embed option from sharing on mobile
- would be great if we can keep changes to the data options strictly to visual treatments and not change functionality or layout (e.g. changing panel structure, adding apply changes buttons, etc)

**Comment by sashasashasasha** [comment]
Figma mockups [here](https://www.figma.com/file/HW0OBYrl7vO8DlrPEqYIl3/SEDA-v4-1.1.0-Explorer-Design?node-id=29%3A637) Page - 'FINAL MOCKUPS'
