### ISSUE TITLE
Add "zoom to location" buttons

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/seda-map#400]
Currently, we have a "zoom to contiguous U.S." button, but we also need buttons for

- zoom to Alaska
- zoom to Puerto Rico
- zoom to Hawaii

![image](https://user-images.githubusercontent.com/21034/104488688-94c5cd80-5583-11eb-952d-69dd518bf5d0.png)

# Tasks
- [x] add the buttons mentioned above
- [x] add a tooltip to each of the buttons that reads out "zoom to {ZOOM_AREA}"

icons available in [figma](https://www.figma.com/file/HW0OBYrl7vO8DlrPEqYIl3/SEDA-v4-1.1.0-Explorer-Design?node-id=31%3A776)

**Comment by sashasashasasha** [comment]
I have added them to a page called 'New icons' in the [same file as the mobile mockups. ](https://www.figma.com/file/HW0OBYrl7vO8DlrPEqYIl3/SEDA-v4-1.1.0-Explorer-Design?node-id=31%3A776)
