### ISSUE TITLE
Integrate existing analytics events

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#403]
@Lane please add details/more info here for what needs to be done :)

**Comment by Lane** [comment]
Analytics events are here: https://docs.google.com/spreadsheets/d/1eX2mkNplfAI1GiEcsv9X9_NcDQaLNTDbpu3_0TnzlIA/edit#gid=59992061

The events have already been configured in google tag manager, use [google tag assistant](https://chrome.google.com/webstore/detail/tag-assistant-by-google/kejbdjndbnbjgmefkgdddjlbokphdefk?hl=en) to verify events are logged.  

Required tasks include:

- review events in spreadsheet, and check if any of the events are currently firing (most, if not all will not be firing as they have been stripped out during refactor)
- for events that are not firing, add code that logs the proper analytic event

e.g. metricSelected
```js
dataLayer.push({event: 'metricSelected', metricSelection: 'avg' })
```

Note: this is probably best implemented using a hook (e.g. `useAnalytics()`) that is initialized on `SedaExplorer`.

e.g. useAnalytics that triggers events when metric changes:

```js
export default function useAnalytics() {
  const [metric] = useMetric()
  // triggered every time the metric changes
  useEffect(() => {
    dataLayer.push({event: 'metricSelected', metricSelection: metric })
  }, [metric])

  // ... analytics triggers for remaining events
}
```
