### ISSUE TITLE
Location Comparison dialog: Export CSV doesn't reflect data shown in table

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#412]
Steps to reproduce:
1) Go to side nav > Location filter > choose 3 locations by county (Los Angeles county, Riverside county, San Diego county) > click Compare Locations https://dev.edopportunity.org/explorer/#/map/none/counties/avg/ses/all/8/32.99/-116.83/06037,34.359,-118.18+06065,33.754,-115.075+06073,32.994,-116.831

2) In dialog, choose subgroup "Native American" 
![image](https://user-images.githubusercontent.com/76966798/104382374-d3f01200-54e2-11eb-8522-e1fdefa6fdb2.png)

3) Click "Export CSV"

**Expected behavior:** the CSV export values should match the dialog values
**Actual behavior:** the export shows the Native American learning rates as:
 - Los Angeles county: .989
 - Riverside county: .926
 - San Diego county: .943
![Export learning rates](https://user-images.githubusercontent.com/76966798/104383006-fafb1380-54e3-11eb-9704-1f400d6a0337.png)

But the dialog shows the Native American learning rates as:
 - Los Angeles county: -1.1%
 - Riverside county: -7.4%
 - San Diego county: -5.7%
The values should match between the export and dialog. The client asked that both the CSV export and the dialog show the adjusted values (NOT the actual values from the raw data). 

![Dialog learning rates](https://user-images.githubusercontent.com/76966798/104383024-02bab800-54e4-11eb-8f0f-244ba354400c.png)

**Comment by Lane** [comment]
@laurendoone thanks for logging this, it's something we should check with the client on.

- Currently, it is exporting all of the data we have for the locations.  I was unsure if this is how they want it, or if I should limit to what's visible.
- The values match what is provided in their official data, however within the explorer learning rate values are adjusted to be the difference from 1, where 1 represents the national average. (e.g. 0.989 - 1 = -0.011 = 1.11%). Definitely confusing for users, but I'm not sure if they want the data export to be consistent with the values in the official SEDA data or what's in the explorer.

**Comment by laurendoone** [comment]
Got it, moving this to Blocked for now while I confirm behavior with client.

**Comment by laurendoone** [comment]
@Lane discussed with client, they asked that the location comparison dialog and the CSV export match, and show the adjusted values (NOT the raw values from the data) to avoid user confusion.

**Comment by Lane** [comment]
sounds good, remaining tasks for this issue are:

- update any `grd` values to be consistent with explorer (pass them to the `formatPercentDiff` function)
- add any missing header column names to the [explorer language](https://docs.google.com/spreadsheets/d/1L633lO5wfQGLbaVnaSnIg9TrprX9k4Ie8qe_CLDmQN8/edit#gid=0).  (add them in the sheet then run `npm run prebuild` to generate language file)
