### ISSUE TITLE
State PDF export is missing graphs/data

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#428]
Download Report PDF for states shows graphs of school data - should these be updated to show a graph with states that calls out the reported state?

**Comment by Lane** [comment]
@laurendoone removing myself from this one.  there is a good chunk of work to do in the [seda-export](https://github.com/Hyperobjekt/seda-export) repo for this.

currently it generates report for counties, districts, and schools.  someone will need to add functionality to handle states.  we do not need anything additional from the client to implement this.
