### ISSUE TITLE
Reverse white and black scores

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#431]
on the left charter https://dev.edopportunity.org/explorer/#/chart/none/counties/avg/seg/wb/3.15/37.39/-96.78/, white scores are on the vertical axis and black on horizontal.  We’d like it the other way (white scores on horizontal and black scores on vertical) as it is in the current site https://edopportunity.org/explorer/#/chart/us/districts/avg/ses/wb/3.69/38.3/-95.97.

**Comment by Lane** [comment]
closed by #430
