### ISSUE TITLE
[DESIGN] Location panel: update typography

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#434]
Feedback from James on the location panel: the highlighted subheader here could be better in terms of typography (and anywhere else where this style is in use):
![image](https://user-images.githubusercontent.com/76966798/104643476-57d00880-5661-11eb-9c38-86dcfb0dbec3.png)

**Comment by Lane** [comment]
@laurendoone any clarification on what "could be better" means?

**Comment by laurendoone** [comment]
@sashasashasasha  do you have any feedback on this? same font/different weight?
