### ISSUE TITLE
[DESIGN] Update data filters

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#438]
Feedback from James: Wonder if Sasha would have thoughts on these filtering controls (and typography). Both type and controls look kind of generic to me—controls are the stock Material UI ones, I believe, which is fine but has that off-the-shelf look. If Sasha has other ideas and it's not a huge pain to implement (it may be), I'm open to customizing and making these prettier.

![image](https://user-images.githubusercontent.com/76966798/104645678-37ee1400-5664-11eb-9a73-0c924e220f5e.png)

**Comment by Lane** [comment]
@james-minton @sashasashasasha see issue #383 for my comments on UX and visual improvements for filter panel

**Comment by laurendoone** [comment]
@sashasashasasha as part of this design update, can you also incorporate the following into a mockup? For metric sliders, use color gradient for the currently active metric, use more neutral color for others.

**Comment by sashasashasasha** [comment]
@laurendoone  Just to make sure I understand correctly. A colour gradient like this? <img width="681" alt="Screenshot 2021-01-15 at 19 34 00" src="https://user-images.githubusercontent.com/12460782/104770580-b03dfd80-5768-11eb-9a51-52602dda720e.png">

**Comment by james-minton** [comment]
@sashasashasasha I like this!

**Comment by sashasashasasha** [comment]
@james-minton I think this could be improved but this is what you mean right?

**Comment by james-minton** [comment]
Yeah; but also Lane had suggested

> was thinking we could drop labels on the markers themselves and have static markers below the bar.  similar to our legend, but whichever works

![image (2)](https://user-images.githubusercontent.com/33635008/104779280-d5247780-574c-11eb-992a-8ba03f66de2c.png)

**Comment by sashasashasasha** [comment]
@james-minton One issue with using the gradient for this scales is that the colours don't have enough contrast so they doesn't pass WCAG AA. This is especially a problem if the outside sections of the slider have less opacity to show they are not selected. The blue has enough contrast.
<img width="653" alt="Screenshot 2021-01-18 at 23 23 28" src="https://user-images.githubusercontent.com/12460782/104970669-32862600-59e4-11eb-861a-f2ff152e0da5.png">
<img width="658" alt="Screenshot 2021-01-18 at 23 24 21" src="https://user-images.githubusercontent.com/12460782/104970705-5184b800-59e4-11eb-827c-25f03112c145.png">

**Comment by james-minton** [comment]
@sashasashasasha looks nice nevertheless. Would it help to add a border to the scale, perhaps?

Also I like the color on the control dots themselves, but I think we need to show both the min/max values for the scale, and the values for the filters themselves.

I _think_ what @Lane was suggesting was putting the numeric values for the filters _inside_ the control handles (which are currently mocked up as the 2 circles on the scale). Barring that, maybe on top of the control handles?

**Comment by Lane** [comment]
@sashasashasasha @james-minton was thinking something along the lines of this:

![image](https://user-images.githubusercontent.com/21034/104972272-1ebbcf00-59a6-11eb-9a88-0c56683d0e04.png)

visual styles tweaked to however @sashasashasasha sees appropriate, but functionality as follows:

- the actual value of the metric can be hidden, and shown when dragging ![image](http://g.recordit.co/dkrURAmMxU.gif)
- ticks below add context and general idea of values
- - color contrast for the bar isn't a huge concern, the WCAG color contrast rules mostly apply to text, but it would be a concern if the control dots do not have sufficient contrast (will need a border or high contrast fill color)

**Comment by sashasashasasha** [comment]
@Lane @james-minton  
- Showing the actual value only when dragging is a nice touch. Would these sliders be used on tablet too? Having the numbers above the slider helps when dragging with a finger on tablet. 
- Do all the ticks need to be below the sliders? This adds complexity. What if only min and max are under the sliders or is this not enough information?

<img width="727" alt="sliders 1" src="https://user-images.githubusercontent.com/12460782/105209776-22845880-5b42-11eb-830e-f5efd29000cc.png">
<img width="706" alt="sliders 2" src="https://user-images.githubusercontent.com/12460782/105209787-2617df80-5b42-11eb-8b64-7caa3cc06b56.png">

**Comment by Lane** [comment]
@sashasashasasha looking good! personally i like 1 or 2.  options 3 and 4 have a lot of use of shadows and shapes that we don't currently have in any of our other UI controls so i think they would feel a little out of place.

in regards to your questions / comments:
- yes the values would show on text / mobile when dragging with your finger
- all the ticks are not necessary, but i feel like they provide useful markers to provide context about roughly what values are currently set.  at minimum i think ticks for the minumum, midpoint, and maximum should be there.
- yes, the knobs should have an active hover / focus state (e.g. bright blue as you suggested)

**Comment by james-minton** [comment]
Agreed, looking good @sashasashasasha and either 1 or 2 works for me. Not seeing much difference between those 2, except for color of SES range? Maybe we should go with blue for that one, since it's an "always active" metric, in contrast to the 3 metrics above it.

**Comment by sashasashasasha** [comment]
Yes the only difference between 1 and 2 is the colour of the SES range. I have put the mockups in the page 'FINAL MOCKUPS' in the https://www.figma.com/file/HW0OBYrl7vO8DlrPEqYIl3/SEDA-v4-1.1.0-Explorer-Design?node-id=29%3A637
