### ISSUE TITLE
Help panel includes strange characters

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#441]
Steps to reproduce:

- In Explorer header, click HELP button to open panel
- Expand the first question, see characters are included in the text:
![image](https://user-images.githubusercontent.com/76966798/104664849-1e10f900-5685-11eb-994b-54889e97e041.png)

**Comment by Lane** [comment]
fixed this up by replacing the weird character in the google sheet

**Comment by laurendoone** [comment]
@Lane  is it possible to remove the extra spaces too? Also, do we know what the "showing" icon is supposed to be? Doesn't seem quite right...

![image](https://user-images.githubusercontent.com/76966798/104970054-157b3400-599f-11eb-9f61-dd3056777101.png)

**Comment by Lane** [comment]
@laurendoone yes, these can be updated in the [explorer language spreadsheet](https://docs.google.com/spreadsheets/d/1L633lO5wfQGLbaVnaSnIg9TrprX9k4Ie8qe_CLDmQN8/edit#gid=0).

many of these entries describe interface elements in the first iteration of the explorer and need to be updated
