### ISSUE TITLE
Location comparison dialog: Load similar locations does not work for Puerto Rico

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#442]
Steps to reproduce:

- Select county filter
- Select some county + a Puerto Rico county
- In Location panel, click COMPARE LOCATIONS
- In location comparison pop up, click Puerto Rico county and "Load Similar" button
- See Loading button load indefinitely

Expected results: up to 5 similar counties to the PR county load
Actual results: nothing loads, button says "loading" indefinitely

Is this related/similar data issue to https://github.com/Hyperobjekt/seda-map/issues/413?

**Comment by Lane** [comment]
@laurendoone yes, same issue as #413.  Puerto Rico is new in this release and we don't currently have the "similar locations" data set for it.

**Comment by laurendoone** [comment]
Got it - is this something we're expecting in final data set?

**Comment by Lane** [comment]
Yes!

**Comment by Lane** [comment]
@laurendoone the latest dataset they provided includes similar places for counties, districts, and schools, but does not include similar places for states.

we need to:
- check if they want to allow the user to load similar places at the state level
  - if yes, they need to provide a `StatesMatch.csv` file similar to the other match files
  - if no, we need to disable the "load similar places" button when a state is selected (and add a tooltip hint explaining why)

**Comment by Lane** [comment]
should be fixed with latest data update
