### ISSUE TITLE
Location comparison dialog: Add description to Socioeconomic Status column

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#443]
The client would like to add a description under the Socioeconomic Status column header in the location comparison dialog. 

Copy: average SES in the community, not specific to any group

![image](https://user-images.githubusercontent.com/76966798/104772739-bf04c000-5728-11eb-8a10-3d6444a2fcc1.png)

**Comment by Lane** [comment]
can add a description in for sure, though this one seems inaccurate.  the
socioeconomic status value corresponds to the selected subgroup

e.g. in the screenshot above, the selected subgroup is "Native American",
so it is showing the socioeconomic status value for the Native American
subgroup.  If the hint text is "average SES in the community, not specific
to any group", does that mean they do not want this value to be relative to
the currently selected subgroup?

**Comment by laurendoone** [comment]
From client: To your question about all subgroups in the export CSV file, that is OK with our team. However, sean flagged that SES measure is not specific to subgroups. So we are wondering if your team could include a note about the SES estimate- something like “average SES in the community, not specific to any group”

**Comment by laurendoone** [comment]
So.. should I update the client that the value is actually specific to the subgroup? Or am I misunderstanding?

**Comment by Lane** [comment]
hmm.. i'm not sure, maybe i am also misunderstanding.  we have a SES value for each subgroup, which would make me think it is specific to the subgroup?
