### ISSUE TITLE
Mobile: comparison dialog

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/seda-map#454]
Location comparison is not very usable on mobile.

Changes required:
- open the dialog in full screen on mobile
- stack toolbar items into 3 rows:
  - Comparison subgroup / gap
  - Location search
  - Load similar locations + export CSV
- add sticky headers on the table so they are always in view
- table has overflow so it can be scrolled up/down/left /right while other dialog elements stay in place

**Comment by laurendoone** [comment]
@touchRED layout looks good on mobile! but when I click EXPORT CSV, the document that is downloaded to my iphone is blank. Can you reproduce or are you able to actually download/view the csv on your phone?
