### ISSUE TITLE
Cannot search/filter for Puerto Rico (when filtering by state)

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#457]
In the "find a location" search box, if you type in Puerto Rico, nothing appears under "State". You have to filter by a specific city instead of being able to filter by the entire state.

Steps to reproduce:
1. Go to Find a Location search box in the top nav
2. Type "puerto rico"
3. See in the results, Puerto Rico does not appear under "State". Only specific cities appear under "Cities"

Expected result: Puerto Rico appears under "State" in the search results so you can see results by state
Actual result: only cities in Puerto Rico appear under "Cities"

![Screen Shot 2021-01-18 at 1 44 23 PM](https://user-images.githubusercontent.com/76966798/104965616-ee6b3500-5993-11eb-84d6-860c9a2750df.png)

**Comment by Lane** [comment]
we're currently using an old search dataset, waiting for the final data set before we push the search indexes due to the cost associated with it.

**Comment by Lane** [comment]
deployed to search, should be fixed
