### ISSUE TITLE
Find a location search results incorrect

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#458]
Feedback from client: when I type in the box to filter districts by state, when I type the letter “P”, the name suggested is “Philadelphia” – which isn’t a state (should be “Pennsylvania”); when I type “M”, one option is “MS” (instead of “MIssissippi”) – please check this (it should also list Puerto rico under “P”)

Steps to reproduce:
1) In "Find a location" search box in top nav, type "P". See under "States", Philadelphia appears (should be Pennsylvania). Also, Puerto Rico should be listed in addition to Pennsylvania
2) In "Find a location" search box in top nav, type "M". See under "States", MS appears (should say the full state name instead of abbreviation)

**Comment by Lane** [comment]
our search is based off of the data they provide.  i will check their state level data before we deploy the search engines to ensure state names are correct

**Comment by Lane** [comment]
deployed new search data, should be fixed
