### ISSUE TITLE
Charts do not include 0 on the axes

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#459]
Feedback from client: when I look at black-white gap within states, the chart on the right (gap vs X) has a y-axis scale that doesn’t include 0; when X is SES, the x-axis scale doesn’t include 0 (more generally – I think we should generally make sure the gap charts include 0 on the axes.

to do: each chart should include 0 on the axes

**Comment by Lane** [comment]
@laurendoone is this sean's request?

previously it was requested that we change the axis labels to "national average" and similar labels to help with comprehension and understanding what the "0" value actually means.

can switch it back to "0" if they've decided that would be better, though i think it could impact comprehension.

**Comment by laurendoone** [comment]
@Lane  yes, sean's request. I'll let them know we changed this intentionally and see if he wants to change it back

**Comment by Lane** [comment]
@laurendoone this can be updated by replacing the values in the explorer language spreadsheet with "0", under the following keys:

- `AXIS_SES_GAP_MID`
- `AXIS_SEG_GAP_MID`
- `AXIS_SES_MID`
- `AXIS_MIN_GAP_MID`

**Comment by laurendoone** [comment]
@Lane  client said: i'm not asking to change the labels. i'm asking to change the axis range/scale -- so that 0 is included in the range.

Does the update to the explorer language spreadsheet accomplish this request?
