### ISSUE TITLE
Location panel: only use 1 decimal place for confidence intervals

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#460]
The client would only like to show 1 decimal place for confidence intervals on the location panel

![image](https://user-images.githubusercontent.com/76966798/104966448-c086f000-5995-11eb-816f-1e0bc6111d4f.png)

**Comment by Lane** [comment]
i've updated based on metric:

- Average test scores (updated to 1 significant figure, 0.068 => 0.07)
- Learning rates (updated to % with 1 decimal place, 0.042 => 4.2%)
- Trend in test scores (updated to 1 significant figure, 0.048 => 0.05)

can re-open if we need to change to something else

**Comment by laurendoone** [comment]
waiting on client feedback
