### ISSUE TITLE
Implement Explorer copy updates from language sheet

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#464]
The client has some copy edits on the explorer. I added a new tab (changes) and added a new column (c) called "new value" with the requested copy change. Anything that was just a copy change I've already edited in the doc, but the ones remaining in the new tab require some coding because they want to add sub-text to what we already have: https://docs.google.com/spreadsheets/d/1L633lO5wfQGLbaVnaSnIg9TrprX9k4Ie8qe_CLDmQN8/edit#gid=0

**Comment by alegzandach** [comment]
@laurendoone moving to ready for code review as support now exists, just need copy to be added to spreadsheet (i've added entries for these props in the spreadsheet as: *SPECIFIEDLABEL*_DESC e.g FILTER_LABEL_AVG_DESC
