### ISSUE TITLE
Intro screen: copy update

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#466]
On the intro screen, please update the years to 2017-2018:
![image](https://user-images.githubusercontent.com/76966798/104970647-10b77f80-59a1-11eb-9a4a-3f924f5eb2a7.png)

**Comment by Lane** [comment]
@touchRED seeing that this still has the old copy before the assets load.  can you update the copy in `index.html`?

![image](https://user-images.githubusercontent.com/21034/105390222-a899b100-5bcd-11eb-83fc-19bf067c71c7.png)

**Comment by touchRED** [comment]
@Lane whoops, yes can do!
