### ISSUE TITLE
Mobile: find a place search bar is off screen

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#467]
https://user-images.githubusercontent.com/76966798/104971431-9dfbd380-59a3-11eb-80f5-2e809c27380b.MP4

On mobile, the "find a place" search bar in the top nav shifts off screen when in focus

See attached video.

steps to reproduce:
1) on a mobile device (I was using an iPhone X, Chrome, go to the "find a place" search box in the top nav
2) see the search bar shift off screen making it hard to see what you're typing
3) after selecting a location in the results list, see the result appear in the map but it's hard to zoom out in order to get the search bar back into focus on the screen

**Comment by Lane** [comment]
should be able to fix with meta tag update

`<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0"/>`
