### ISSUE TITLE
When filtering by state, show all schools, districts, counties

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#470]
Feedback from client: when we filter by state, I’d like all units (schools/districts/counties) in the country to still show up (similar to current explorer when a state is selected).

**Comment by laurendoone** [comment]
@Lane  do you mind adding some detail here on what needs to be done so connor/alex can take this over?

**Comment by laurendoone** [comment]
@Lane Sean would like to have the underlay but asked if there's any other options that won't impact performance as much as it is on DEV right now? If not, they'll go with option 3: try implementing the in-between option to show the background for largest 3000 states/counties/districts/schools and it only appears when the filter has less than 3000 results.

**Comment by laurendoone** [comment]
@Lane client agreed to go with option 3 for launch. can you implement or do you want to pass over to connor/alex?

**Comment by Lane** [comment]
I've updated this on dev.edopportunity.org/explorer

**Comment by laurendoone** [comment]
thank you!
