### ISSUE TITLE
Create 3 versions of site

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#476]
We'll need to have 3 versions of the site for various audiences/launch dates:

1) Embargoed site for Jan 20 or 21st testing - update the existing embargoed site with all fixes/updates/final data to date, for ProPublic to help with user testing. Explorer includes BIE and NAM estimates.

2) Preview site for February 3 launch (separate version to send to journalists) - Explorer has BIE and NAM estimates **hidden**. Hide "Native American" subgroup and "White-Native American" gap for state/county/school districts, and hide school-level estimates for BIE schools.

3) Production site for Feb 8 launch - replaces existing edopportunity.org version, Explorer has BIE and NAM estimates **hidden**. Hide "Native American" subgroup and "White-Native American" gap for state/county/school districts, and hide school-level estimates for BIE schools.

**Comment by Lane** [comment]
@laurendoone for item 1, does this need to be the entire site, or just the explorer?

**Comment by laurendoone** [comment]
For now let's just update the explorer. No password protection is needed at this time (the existing link isn't pw protected anyway, right?) unless they specifically ask for it

**Comment by Lane** [comment]
currently the embargoed explorer link with Native American / BIE data is
password protected at client request (embargoed.edopportunity.org)

**Comment by laurendoone** [comment]
@Lane oh ok! in that case, I guess we should keep it password protected
