### ISSUE TITLE
Add "What's new in 4.0" in Explorer menu

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#486]
Can we add a link in the Explorer menu "What's new in 4.0" so it matches the menu in the site? This should link to the Changelog page

On the site menu:
![image](https://user-images.githubusercontent.com/76966798/105389048-3bd1e700-5bcc-11eb-9dde-03d4ae03090c.png)

But on the Explorer menu, it's missing:
![image](https://user-images.githubusercontent.com/76966798/105389116-52783e00-5bcc-11eb-98a4-431140448919.png)

**Comment by Lane** [comment]
@laurendoone yes, we have this as part of #433

@alegzandach has a pull request open for this, but i can't merge in until conflicts are resolved.

**Comment by laurendoone** [comment]
@Lane got it, will close this issue then, thanks!
