### ISSUE TITLE
Adjust SES labels depending on group selected

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/seda-map#489]
SES is not available for all subgroups (e.g. Asia, non-poor, poor, male, female).  currently, the X axis label says "{SUBGROUP} socioeconomic status" (e.g. "Asian students' families socioeconomic status")

when SES is not available for a given subgroup, the X axis label should read "Overall families' socioeconomic status".

In the comparison dialog, the hint text for "Socioeconomic status" also needs to be updated, to reflect the current subgroup or display "overall" for subgroups with no related SES.  The wording should also update when a gap is selected, to reflect that the value is a gap in SES and not the SES for any specific subgroup

**Comment by laurendoone** [comment]
Notes from client meeting:

SES values are subgroup specific for the following groups, so we can show the values in the Explorer:
- Black/white/hispanic 

SES values are not sub-group specific for the following groups, so we just show an average in the Explorer:
- Asian
- Native American
- poor
- non-poor
- male
- female 

We need to update the copy in the chart labels and location comparison dialog SES column description to account for these differences and make it clear to a user what the values mean. 

Suggestion from client/TO DO:
- If subgroup selected is white, black or hispanic, then copy says "Average SES among all [insert subgroup name] families in the community"
- If subgroup selected is male or female, then copy says "Average SES among all families in the community"
- If no subgroup is selected (all is selected), then copy says "Average SES among all families in the community"
- If subgroup selected is poor or non-poor, then copy says "N/A"
- If a gap is selected, then copy says "Average [insert gap name] gap SES in the community" e.g. if the white-black gap was selected, copy says "Average white-black gap SES in the community"

**Comment by touchRED** [comment]
@Lane @laurendoone A couple questions about this, based on the "suggestions from client" section:

It seems like the first 3 bullets might be solved by editing the language sheet, but the 4th bullet makes me wonder if they're differentiating which copy changes on the chart's x axis, the comparison table, or both. For example:

> If subgroup selected is poor or non-poor, then copy says "N/A"

Obviously we don't want to display "n/a" on the chart's x axis

**Comment by Lane** [comment]
@touchRED here is a more clear breakdown of where changes are needed:

# Compare Dialog

under socioeconomic status table header, for subgroups:

- all, male, or female: Average SES among all families in the community
- white, black, hispanic, asian, or native american: Average SES among all `{{SUBGROUP}}`  families in the community
- poor or non-poor: Average SES not available for `{{SUBGROUP}}` families
- gaps (except for poor - non-poor): Average `{{GAP}}` gap SES in the community
- poor - non-poor gap: Average `{{GAP}}` gap in SES not available

the values in the table should correspond to the label, e.g:

- all, male, or female: uses `all_ses` value
- white, black, hispanic, asian, or native american uses `{{SUBGROUP}}_ses` value (e.g. `w_ses` for white SES)
- poor or non-poor show "N/A" for all locations (if you use `p_ses` and `np_ses` it should show "N/A" because those values are not available) 
- gaps show gap value where avaialble `{{GAP}}_ses` (e.g. `wb_ses` for white - Black SES)
- gaps with no SES value (eg. poor - non-poor) show "N/A"

# Chart Axis
- all, poor, non-poor, male, or female: "Average families' socioeconomic status"
- white, black, hispanic, asian, or native american: "`{{SUBGROUP}}` Families' Socioeconomic Status"
- gaps: "`{{GAP}}` Gap in Socioeconomic Status"
