### ISSUE TITLE
Location panel: threshold for top 3 key metrics?

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#490]
Request for Lane: can you find the thresholds used for the top 3 key metrics in the location panel? client wants to make sure they are still accurate

**Comment by Lane** [comment]
@laurendoone here are the value ranges to determine "average" in the summary portion of the location panel:

- average test scores: `-0.25 - 0.25`
- learning rates: `0.965 - 1.035`
- trend in test scores: `-0.025 - 0.025`
- socioeconomic status: 
  - `< -2.5`: very far below average
  - `-2.5 - -1.5`: far below average
  - `-1.5 - -0.5`: below average
  - `-0.5 - 0.5`: average
  - `0.5 - 1.5`: above average
  - `1.5 - 2.5`: far above average
  - `>2.5`: very far above average

**Comment by laurendoone** [comment]
thank you!
