### ISSUE TITLE
Change chart title 

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#495]
Feedback from client: The top left legend says "Average students' average test scores vs. socioeconomic status" when average scores are selected. Can we change the copy to: "Average students' test scores vs. socioeconomic status" 

![image](https://user-images.githubusercontent.com/76966798/105526566-76ed1c80-5c97-11eb-9542-7440c2b0665f.png)

**Comment by Lane** [comment]
@alegzandach 

in this case, we should add a conditional for the chart titles when the scatterplot metric is "Average Test Scores" (`avg`).

- if the metric for the chart is `avg` and it is not a gap, then we should use `SCATTERPLOT_TITLE_AVG` as the language key.  
- if the metric for the chart is not `avg` and not a gap, then we should use `SCATTERPLOT_TITLE` as the language key.

![image](https://user-images.githubusercontent.com/21034/106186358-03e11b80-6159-11eb-8d67-65df02132aad.png)

you might also need to add an additional conditional if the demographic equals `all` if the wording is weird when that option is selected.  it should read "Average Students' Test Scores vs..." when `all` is selected.
