### ISSUE TITLE
Compare locations CSV: remove all Native American estimates

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#498]
Remove all estimates related to Native Americans in the Compare Locations export since we are not going live with Native American estimates in this release

Steps to reproduce:
1) Select 2+ places on the map
2) In location panel, click COMPARE LOCATIONS
3) in location comparison dialog, click EXPORT CSV 
4) in export, see there are still columns with Native American data. example here - all columns in red should be removed: https://docs.google.com/spreadsheets/d/1du-pA9ANQsHFiLy4HF0ofMWGOlxztk0QsHaqZrFwdiY/edit#gid=1772039747

Expected result: the CSV export does not include any native american estimates or data

**Comment by Lane** [comment]
when implementing, use the REACT_APP_EMBARGOED environmental variable to determine if the Native American data should be included.

e.g.

```js
if (process.env.REACT_APP_EMBARGOED) {
  // include Native American data
} else {
  // strip Native American data
}
```
