### ISSUE TITLE
Location panel: change overview language

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#511]
Feedback from client:
Location panel "Educational Opportunity Overview" section: I find the text on these panels hard to read/interpret:

Example:

This is the current language and layout:
![image](https://user-images.githubusercontent.com/76966798/106070015-8796fb80-60b8-11eb-8b59-3f932e558ea1.png)

Instead, the client wants to to break out the information like the following:
 
Overall:
- Test scores are lower than U.S. average
- Learning rates are slower than U.S. average
- Test scores are declining over time 

Compared to places with similar socioeconomic status:

- Test scores are **lower**
- Learning rates are **lower**
- Test scores are declining faster

TO DO: Add headers "Overall" and "Compared to places with similar socioeconomic status" to the location panel (those do not currently exist).

**Comment by touchRED** [comment]
@laurendoone it looks like these labels are tied to the cells prefixed with 'SUMMARY_' in the google language sheet:

![image](https://user-images.githubusercontent.com/1114157/106171386-794fea80-615f-11eb-8f5b-52a5a5c808a3.png)

I'm unsure how we might get away with bolding certain words though. Obviously there are a couple ways we could go about it but I wonder if it would just convolute the language management further. cc @Lane

**Comment by Lane** [comment]
@touchRED you should be able to use HTML in these.  e.g. `test scores are <strong>lower</strong>`

**Comment by laurendoone** [comment]
@touchRED @Lane ah ok, i can make those edits in the explorer language spreadsheet then! but if they want the headings "overall" and "compared to places with similar socioeconomic status", does that require coding?

**Comment by laurendoone** [comment]
@touchRED style like so:
![image](https://user-images.githubusercontent.com/76966798/106206898-b4f5af00-6175-11eb-9d2d-017881539007.png)
