### ISSUE TITLE
Embargoed site: see entire scatterplot when filtering

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#517]
Feedback from client: i don't like how constrained the range gets when filtering. should still see whole scatterplot. 

see eg:
https://embargoed.edopportunity.org/#/chart/bie/schools/avg/frl/all/14/33.36/-110.45/040696001656,33.358,-110.454

**Comment by laurendoone** [comment]
@Lane i can assign this to alex/connor but first wanted to check if there's anything they need to know about the embargoed site before working on it?

**Comment by Lane** [comment]
this was a quick adjustment, just updated and pushed to embargoed link
