### ISSUE TITLE
Embargoed site: Native American data does not appear 

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#523]
On the embargoed site, I don't see Native American subgroup/gap appear in the data filters:
![Screen Shot 2021-02-01 at 7 24 29 AM](https://user-images.githubusercontent.com/76966798/106479063-bd443780-645e-11eb-8bcb-b02f03aa7a72.png)

**Comment by Lane** [comment]
fixed this up and pushed an update to embargoed
