### ISSUE TITLE
Help panel: update copy

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#525]
Please update the Help topics - they are currently outdated since they reference the old UI

You can update the copy directly in the Explorer Language Spreadsheet (next time we do a build, the copy updates will automatically appear in dev/staging so this is the more efficient route): https://docs.google.com/spreadsheets/d/1L633lO5wfQGLbaVnaSnIg9TrprX9k4Ie8qe_CLDmQN8/edit#gid=0

OR you can update the copy in this doc (please highlight your edits) and I'll transfer the edits to the Explorer Language spreadsheet: https://docs.google.com/document/d/1rucLX2_loTBVc47RJKDuCLRMe0cCnkYZ7YtR3QOuKS8/edit?ts=60074ed6#

**Comment by james-minton** [comment]
Have edited the usability help topics to better reflect current Explorer version. 

Question: how might one best add an entry? Would it be enough to follow the existing pattern (and potentially reorder the list of questions to put a new one where I want it in the sequence), or is it more involved?

Seems like we should have an entry for the new filter controls.

**Comment by laurendoone** [comment]
@james-minton if we want to add more help topics, some light coding will be required. I can assign to alex/connor if you can detail what needs to be added and the order (or you can do it but may want to check with alex or lane on what to do as they have done this before)
