### ISSUE TITLE
gradient on filter bars is offset

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/seda-map#531]
**to replicate**
usng latest version of google chrome, open the following link: https://dev.edopportunity.org/explorer/#/map/none/districts/avg/ses/all/3.15/37.39/-96.78/

open up the "data filters" panel.

**expected result**
the grey on the gradient should match up with the midpoint label ("average")

**actual result**
![image](https://user-images.githubusercontent.com/21034/106642274-f9e66080-653c-11eb-9396-8e1719bee518.png)

**Comment by touchRED** [comment]
lol this one looks crazy...the gradient resets if you click the "reset filters" button, which i assume causes the panel to rerender – so the gradient maybe is initialized to its fixed position before the panel slides out??
