### ISSUE TITLE
Help Panel: add more topics

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#533]
Please see 'changes 2' tab in Explorer Language Sheet https://docs.google.com/spreadsheets/d/1L633lO5wfQGLbaVnaSnIg9TrprX9k4Ie8qe_CLDmQN8/edit#gid=996524101

All the copy already exists in the spreadsheet, but we need them to appear on the site.

For all the items marked 'ADD THIS', we need to add to the Help Panel.

**Comment by touchRED** [comment]
@laurendoone it looks like the code brings in *all rows* from the google sheet in the form of `HELP_HOW_Qn` and `HELP_HOW_Qn_A` to render question-answer pairs, so this probably won't require any new code if we want to render them like the rest of the questions in the panel

**Comment by laurendoone** [comment]
@touchRED i'm looking at production (edopportunity.org/explorer) and it *looks* like for this help panel, the copy is referencing the actual chart that the user is viewing. For example, if I change the region in the filter to "school district", then the help copy changes to show "district":
![image](https://user-images.githubusercontent.com/76966798/106793765-b9561800-660c-11eb-99ac-b86e79398de7.png)

And if I change the region filter to "county", then the help copy here changes to say "counties". So I think the copy is referencing/tied to the chart view on the right, and we don't need to include any kind of static image in the help panel itself. Let me know if that makes sense and @Lane plz correct me if I'm wrong!

**Comment by Lane** [comment]
@laurendoone yes this is right, but I removed these items from the help panel on the new version because we now use some additional labelling and hinting to communicate this info.

i don't think it's particularly helpful to repeat this in the help panel, but if it's something they want us to put in that works for me

**Comment by laurendoone** [comment]
@Lane  yeah I told them that it was redundant to have it in the help topics since it's contextual in the map/chart, but they still want to keep all the topics in there :/
