### ISSUE TITLE
Search index: disable 'cities'

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#536]
Feedback from client (open to discussion though): From the scatterplot, if you search for any city, it won't go anywhere. The suggestion is to disable cities on the scatterplot (they direct to map locations but not to scatterplot points) or to default to the district that the city is in.

![image](https://user-images.githubusercontent.com/76966798/106690130-1490f780-6586-11eb-8cd0-ef323cc1f4b6.png)

cc @james-minton @Lane

**Comment by Lane** [comment]
we added this at sean's request, i'm good with either of these solutions:

- remove cities entirely from search
- switch to map view when a city is selected (or map + chart)

**Comment by laurendoone** [comment]
Sean didn't request this - someone else on the team did (Andrew?) I'll ask Thalia whether they actually want to take this into consideration or not before we start working on it.

**Comment by Lane** [comment]
could be, it was a couple years ago.  I remember taking the extra steps to
add cities at someone's request.  anyway, good with making changes to it if
needed.

**Comment by laurendoone** [comment]
@Lane  sean/thalia said: Can you remove cities from the search in scatterplot only? OK for map view

Is that possible?

**Comment by laurendoone** [comment]
@touchRED final decision from client is to remove "cities" from the search altogether.
