### ISSUE TITLE
Location panel: learning rate label is incorrect

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#566]
Bug reported by user: The tool says that learning rates are lower than the average for their socioeconomic status for every school district, even when you select the ones with the highest learning rates for their socioeconomic status.

See example (from staging): https://staging.edopportunity.org/explorer/#/chart/none/districts/grd/ses/all/12/40.99/-73.98/3406840,40.992,-73.979

I am filtering by school district and chose a district higher than the average, but the location panel says learning rates are lower compared to average. 

![Screen Shot 2021-03-09 at 12 05 04 PM](https://user-images.githubusercontent.com/76966798/110531090-0035a280-80d0-11eb-92c7-f6a8afc8f12e.png)

**Comment by Lane** [comment]
@touchRED sorry to hijack this, but wanting to fix this in production as quick as possible.

@laurendoone added in a fix on staging, values should be showing now.  going to move to production to wrap it up.

![image](https://user-images.githubusercontent.com/21034/110687623-91228180-8195-11eb-86e0-3de2c2355bd8.png)
