### ISSUE TITLE
Correct Badly Escaped Characters in Explorer Language Sheet

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/seda-map#589]
[Context](https://hyperobjekt.slack.com/archives/CF64B5K1D/p1621376115002000)

SEDA team identified a couple of spots where some characters are incorrectly escaped, resulting in backslashes being present in the UI. The objective of this ticket is to remove instances where backslashes can be seen on the frontend. 

![unnamed (2).png](https://images.zenhubusercontent.com/605b8464e0e66f4aa2b43f51/60e4ed3a-045d-4ab9-bb13-be603f056017)![unnamed (1).png](https://images.zenhubusercontent.com/605b8464e0e66f4aa2b43f51/b983687e-c52e-4782-98f5-60583b99e6ed)

**Comment by Lane** [comment]
fix for this is live on dev preview / embargoed sites
