### ISSUE TITLE
Update XAxis Label

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/seda-map#591]
[Context](https://hyperobjekt.slack.com/archives/CF64B5K1D/p1621376300005700)
Demetra wants us to change the X axis label on the second chart to "Black-White Gap in Exposure to School Poverty" and I guess the idea is that "White" should be the second demographic in the string in every case -- her reasoning:

> The values on this measure are computed as black-white difference in school poverty rates (which is why the values are positive --- black students attend higher poverty schools on average) but the axis reads “white-black difference in school poverty rates. So that should be changed.

**Objective:** Update the xaxis label in chart below to read "Black-White Gap in Exposure to School Poverty" 

![Screen Shot 2021-05-17 at 6.28.14 PM.png](https://images.zenhubusercontent.com/605b8464e0e66f4aa2b43f51/0cb8fc7c-bd9b-471e-a185-b39db0c41db2)

**Comment by Lane** [comment]
fix for this is live on dev preview and embargoed sites
