### ISSUE TITLE
Explorer Updates

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/seda-map#596]
## Objective
Small updates to the explorer before 4.1 Launch

## Tasks
- [x] In the White-Asian Gap vs Asian-White Gap in school poverty, the x-axis is labeled 20% then -10% then no gap then 10%...etc. The -10% should be +10% to be consistent with plot for other racial groups.
- [x] In the gap vs. other metrics plots, Socioeconomic Status is in proper case in the dropdown, but the others are all lowercase. Can we make that consistent?

**Comment by Lane** [comment]
@ekmason @touchRED i had a bug fix for the explorer so added these in while i was in there.  updates should be live on staging / embargoed
