### ISSUE TITLE
Gap chart tooltips display wrong labels (and data when place is selected)

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/seda-map#618]
**Bug description**

if you hover over a district on the righthand graph here:
https://edopportunity.org/explorer/#/chart/none/districts/avg/seg/wb/12/44.96/-93.26/

it says something like “average test scores; gap between white and black students; 4.76 grade levels above the national average”  it should say the gap is 4.76 grade levels. not “above the national average.

oddly, if I highlight a place, the hover box changes and then shows average scores for black and white students (and not gap in school poverty). I’m not sure it should change when a place is highlighted.

**Expected behavior**

- Tooltip should read "[number] grade levels" instead of "[number] grades above the US average."
- Tooltip should continue to display "[METRIC] / gap between [group1] and [group2]" when a place is selected, and not change to show different data/labels.

**Comment by ubiv64** [comment]
Bug/s addressed and fix in place, please review.

Tracked on branch: https://github.com/Hyperobjekt/seda-map/tree/SEDA-618/GapChartTooltip
