### ISSUE TITLE
PDF Export

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/seda-map#77]
PDF export should contain all sections in the state the user has created.

Steps in this task:
- [x] document structure with outline of sections (June 1)
- [x] layout wireframe for each page (~June 14)
- [x] content for document with any robotext templates (~June 14)
- [x] style / theme to apply to the pdf (~July 1)
- [x] server side endpoint to generate the pdf file (August 1)
- [x] front end integration to trigger pdf generation and download file (August 1)

**Comment by Lane** [comment]
From #163:

- Question: what do we include for each location?
    - Map?
    - Scatterplot?
    - All data points?
- To keep this from sprawling on forever (we’re factoring in up to 7 locations!), should we limit map and scatterplot outputs here to just what the user has configured? And let an included, full table of data points complete the picture for other, non-displayed metrics?

**Comment by Lane** [comment]
@james-minton are you able to handle the first task in this list? 

> document structure with outline of sections

I have it marked as June 1, but can push back if needed.  Also the same thing is needed for #162

**Comment by james-minton** [comment]
Unfortunately I think we'll need an extension on these exports -- need SR's input as to desired contents, and no meeting this week. So probably would not have basic specs on these till 6/5 meeting. 

Should I expedite? Try to get input over Slack? Or do we need to talk this through on call?

**Comment by Lane** [comment]
Should be fine, would like to have the first 3 tasks ready for end of June at the latest so I can start writing the code to generate the export.  Could you set some updated deadlines for the first 4 tasks that fits into the design schedule?  (Same for #162)
